// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE


//OpenComputers

recipes.remove(<OpenComputers:carpetedCapacitor>);
recipes.remove(<OpenComputers:item:62>);

//IC2

recipes.remove(<IC2:itemArmorQuantumHelmet:*>);
recipes.remove(<IC2:itemArmorQuantumChestplate:*>);
recipes.remove(<IC2:itemArmorQuantumLegs:*>);
recipes.remove(<IC2:itemArmorQuantumBoots:*>);
recipes.remove(<IC2:blockMetal>);
recipes.remove(<IC2:blockMachine:14>);
recipes.remove(<IC2:blockMachine:5>);
recipes.remove(<IC2:blockMachine:3>);
recipes.remove(<IC2:blockMachine:2>);
recipes.remove(<IC2:blockMachine>);
recipes.remove(<IC2:itemPlates:6>);
recipes.remove(<IC2:itemPlates:4>);
recipes.remove(<IC2:itemPlates:3>);
recipes.remove(<IC2:itemPlates:2>);
recipes.remove(<IC2:itemPlates:1>);
recipes.remove(<IC2:itemPlates>);
recipes.remove(<IC2:itemToolForgeHammer>);
recipes.remove(<IC2:itemPartCircuitAdv>);
recipes.remove(<IC2:itemPartCircuit>);
recipes.remove(<IC2:itemDynamiteSticky>);
recipes.remove(<IC2:itemDynamite>);
recipes.remove(<GraviSuite:graviChestPlate>);

//Iron chest

recipes.remove(<IronChest:woodIronUpgrade>);
recipes.remove(<IronChest:diamondCrystalUpgrade>);
recipes.remove(<IronChest:copperIronUpgrade>);
recipes.remove(<IronChest:steelGoldUpgrade>);
recipes.remove(<IronChest:copperSteelUpgrade>);
recipes.remove(<IronChest:goldDiamondUpgrade>);
recipes.remove(<IronChest:diamondObsidianUpgrade>);
recipes.remove(<IronChest:ironGoldUpgrade>);
recipes.remove(<IronChest:ironSteelUpgrade>);
recipes.remove(<IronChest:obsidianNetheriteUpgrade>);
recipes.remove(<IronChest:BlockIronChest:8>);
recipes.remove(<IronChest:BlockIronChest:6>);
recipes.remove(<IronChest:BlockIronChest:5>);
recipes.remove(<IronChest:BlockIronChest:4>);
recipes.remove(<IronChest:BlockIronChest:2>);
recipes.remove(<IronChest:BlockIronChest:1>);
recipes.remove(<IronChest:BlockIronChest>);

//Big Reactors

recipes.remove(<BigReactors:BRTurbinePart:5>);
recipes.remove(<BigReactors:BRTurbinePart>);
recipes.remove(<BigReactors:BRTurbinePart:1>);
recipes.remove(<BigReactors:BRTurbinePart:2>);
recipes.remove(<BigReactors:BRTurbinePart:3>);
recipes.remove(<BigReactors:BRTurbinePart:4>);
recipes.remove(<BigReactors:BRTurbineRotorPart:1>);
recipes.remove(<BigReactors:BRTurbineRotorPart>);
recipes.remove(<BigReactors:BRIngot:1>);
recipes.remove(<BigReactors:BRReactorPart:2>);
recipes.remove(<BigReactors:BRReactorPart:1>);
recipes.remove(<BigReactors:BRReactorPart>);
recipes.remove(<BigReactors:BRReactorPart:3>);
recipes.remove(<BigReactors:YelloriumFuelRod>);

//Solar Expansion

recipes.remove(<SolarExpansion:solarCoreAdvanced>);
recipes.remove(<SolarExpansion:solarCoreUltimate>);

//Applied energistics

recipes.remove(<appliedenergistics2:tile.BlockCraftingUnit:1>);
recipes.remove(<appliedenergistics2:tile.BlockEnergyAcceptor>);
recipes.remove(<appliedenergistics2:tile.BlockCraftingUnit>);
recipes.remove(<appliedenergistics2:tile.BlockEnergyCell>);
recipes.remove(<appliedenergistics2:tile.BlockDenseEnergyCell>);
recipes.remove(<appliedenergistics2:item.ItemMultiPart:360>);
recipes.remove(<appliedenergistics2:item.ItemMultiPart:380>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:38>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:37>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:36>);
recipes.remove(<appliedenergistics2:tile.BlockCondenser>);
recipes.remove(<appliedenergistics2:tile.BlockInterface>);
recipes.remove(<appliedenergistics2:tile.BlockMolecularAssembler>);
recipes.remove(<appliedenergistics2:tile.BlockFluix>);
recipes.remove(<appliedenergistics2:tile.BlockInscriber>);
recipes.remove(<appliedenergistics2:tile.BlockDrive>);
recipes.remove(<appliedenergistics2:tile.BlockQuartzGrowthAccelerator>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:35>);
recipes.remove(<appliedenergistics2:tile.BlockController>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:68>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:67>);
recipes.remove(<appliedenergistics2:tile.BlockSingularityCraftingStorage>);
recipes.remove(<appliedenergistics2:item.ItemExtremeStorageCell.Singularity>);
recipes.remove(<appliedenergistics2:item.ItemExtremeStorageCell.Quantum>);
recipes.remove(<appliedenergistics2:item.ItemExtremeStorageCell.Universe>);
recipes.remove(<appliedenergistics2:item.ItemVoidStorageCell>);
recipes.remove(<appliedenergistics2:tile.BlockPatternOptimizationMatrix>);
recipes.remove(<appliedenergistics2:tile.BlockCreativeEnergyController>);
recipes.remove(<appliedenergistics2:item.ItemExtremeStorageCell.Container>);

recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:60>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:59>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:58>);
recipes.remove(<appliedenergistics2:item.ItemMultiMaterial:57>);

recipes.remove(<ae2stuff:Grower>);
recipes.remove(<ae2stuff:Wireless>);
recipes.remove(<ae2stuff:Inscriber>);

//Thermal Expansion & Foundation

recipes.remove(<ThermalExpansion:Device:2>);
recipes.remove(<ThermalExpansion:satchel:3>);
recipes.remove(<ThermalExpansion:Tesseract>);

recipes.remove(<ThermalFoundation:material:140>);
recipes.remove(<ThermalFoundation:material:139>);
recipes.remove(<ThermalFoundation:material:138>);
recipes.remove(<ThermalFoundation:material:137>);
recipes.remove(<ThermalFoundation:material:136>);
recipes.remove(<ThermalFoundation:material:135>);
recipes.remove(<ThermalFoundation:material:134>);
recipes.remove(<ThermalFoundation:material:133>);
recipes.remove(<ThermalFoundation:material:132>);
recipes.remove(<ThermalFoundation:material:131>);
recipes.remove(<ThermalFoundation:material:130>);
recipes.remove(<ThermalFoundation:material:129>);
recipes.remove(<ThermalFoundation:material:128>);
recipes.remove(<ThermalFoundation:material:13>);
recipes.remove(<ThermalFoundation:material:12>);

//Ender IO

recipes.remove(<EnderIO:blockTravelAnchor>);
recipes.remove(<EnderIO:itemMEConduit:1>);
recipes.remove(<EnderIO:itemMEConduit>);
recipes.remove(<EnderIO:itemPowerConduitEndergy:11>);
recipes.remove(<EnderIO:itemPowerConduitEndergy:10>);
recipes.remove(<EnderIO:itemPowerConduitEndergy:9>);
recipes.remove(<EnderIO:itemPowerConduitEndergy:8>);
recipes.remove(<EnderIO:itemPowerConduitEndergy:7>);
recipes.remove(<EnderIO:itemPowerConduitEndergy>);
recipes.remove(<EnderIO:itemBigFilterUpgrade>);
recipes.remove(<EnderIO:itemBigFilterUpgrade:1>);
recipes.remove(<EnderIO:itemBasicCapacitor:4>);
recipes.remove(<EnderIO:itemBasicCapacitor:5>);
recipes.remove(<EnderIO:itemBasicCapacitor:3>);
recipes.remove(<EnderIO:itemBasicCapacitor:9>);
recipes.remove(<EnderIO:itemBasicCapacitor:7>);
recipes.remove(<EnderIO:itemGrindingBall:8>);
recipes.remove(<EnderIO:itemGrindingBallEndergy:5>);
recipes.remove(<EnderIO:itemGrindingBallEndergy:4>);
recipes.remove(<EnderIO:itemGrindingBallEndergy:2>);
recipes.remove(<EnderIO:itemGrindingBallEndergy:3>);
recipes.remove(<EnderIO:itemGrindingBallEndergy>);
recipes.remove(<EnderIO:itemGrindingBallEndergy:6>);
recipes.remove(<EnderIO:itemGrindingBallEndergy:1>);
recipes.remove(<EnderIO:blockIngotStorageEndergy:1>);
recipes.remove(<EnderIO:blockIngotStorageEndergy:2>);
recipes.remove(<EnderIO:blockSolarPanel:2>);
recipes.remove(<EnderIO:blockEndSteelBars>);
recipes.remove(<EnderIO:blockIngotStorageEndergy:3>);
recipes.remove(<EnderIO:blockIngotStorageEndergy:4>);
recipes.remove(<EnderIO:itemMachinePart:2>);
recipes.remove(<EnderIO:itemMachinePart:3>);
recipes.remove(<EnderIO:blockIngotStorage:8>);
recipes.remove(<EnderIO:blockIngotStorageEndergy>);
recipes.remove(<EnderIO:blockIngotStorageEndergy:5>);
recipes.remove(<EnderIO:blockIngotStorageEndergy:6>);
recipes.remove(<EnderIO:item.stellar_pickaxe>);
recipes.remove(<EnderIO:item.stellar_axe>);
recipes.remove(<EnderIO:item.endSteel_axe>);
recipes.remove(<EnderIO:item.endSteel_pickaxe>);
recipes.remove(<EnderIO:item.stellar_sword>);
recipes.remove(<EnderIO:item.endSteel_sword>);
recipes.remove(<EnderIO:item.endSteel_boots>);
recipes.remove(<EnderIO:item.endSteel_leggings>);
recipes.remove(<EnderIO:item.endSteel_chestplate>);
recipes.remove(<EnderIO:item.endSteel_helmet>);
recipes.remove(<EnderIO:item.stellar_boots>);
recipes.remove(<EnderIO:item.stellar_leggings>);
recipes.remove(<EnderIO:item.stellar_chestplate>);
recipes.remove(<EnderIO:item.stellar_helmet>);
recipes.remove(<EnderIO:itemBasicCapacitor:8>);
recipes.remove(<EnderIO:blockPoweredSpawner>);
recipes.remove(<EnderIO:blockTransceiver>);
recipes.remove(<EnderIO:blockEnchanter>);
recipes.remove(<EnderIO:itemBasicCapacitor:2>);
recipes.remove(<EnderIO:itemMachinePart>);
recipes.remove(<EnderIO:itemBasicCapacitor>);

//Extra Utilities

recipes.remove(<ExtraUtilities:enderQuarryUpgrade:6>);
recipes.remove(<ExtraUtilities:enderQuarryUpgrade:7>);
recipes.remove(<ExtraUtilities:enderQuarryUpgrade:8>);
recipes.remove(<ExtraUtilities:bedrockiumIngot>);
recipes.remove(<ExtraUtilities:golden_bag>);
recipes.remove(<ExtraUtilities:dark_portal>);
recipes.remove(<ExtraUtilities:drum:1>);
recipes.remove(<ExtraUtilities:drum>);
recipes.remove(<ExtraUtilities:enderQuarry>);
recipes.remove(<ExtraUtilities:enderCollector>);
recipes.remove(<ExtraUtilities:angelRing:4>);
recipes.remove(<ExtraUtilities:angelRing:3>);
recipes.remove(<ExtraUtilities:angelRing:2>);
recipes.remove(<ExtraUtilities:angelRing:1>);
recipes.remove(<ExtraUtilities:angelRing>);
recipes.remove(<ExtraUtilities:peaceful_table_top>);
recipes.remove(<ExtraUtilities:endConstructor>);
recipes.remove(<ExtraUtilities:temporalHoe>);
recipes.remove(<ExtraUtilities:creativebuilderswand>);
recipes.remove(<ExtraUtilities:builderswand>);

//RailCraft

recipes.remove(<Railcraft:machine.alpha:13>);
recipes.remove(<Railcraft:machine.alpha>);
recipes.remove(<Railcraft:machine.alpha:2>);
recipes.remove(<Railcraft:cube:9>);

//Advanced Solar Panel

recipes.remove(<AdvancedSolarPanel:BlockAdvSolarPanel:1>);
recipes.remove(<AdvancedSolarPanel:asp_crafting_items:13>);
recipes.remove(<AdvancedSolarPanel:asp_crafting_items:12>);
recipes.remove(<AdvancedSolarPanel:BlockAdvSolarPanel:5>);
recipes.remove(<AdvancedSolarPanel:BlockAdvSolarPanel:6>);
recipes.remove(<AdvancedSolarPanel:BlockAdvSolarPanel:8>);
recipes.remove(<AdvancedSolarPanel:BlockAdvSolarPanel:9>);
recipes.remove(<AdvancedSolarPanel:BlockMolecularTransformer>);
recipes.remove(<AdvancedSolarPanel:BlockAdvSolarPanel:3>);

//MineFactoryReloaded

recipes.remove(<MineFactoryReloaded:machine.0:13>);
recipes.remove(<MineFactoryReloaded:machine.2:10>);
recipes.remove(<MineFactoryReloaded:plastic.sheet>);
recipes.remove(<MineFactoryReloaded:machine.2>);

//Botania

recipes.remove(<Botania:terraPick>);
recipes.remove(<Botania:flightTiara>);
recipes.remove(<Botania:flightTiara>);
recipes.remove(<Botania:pool:2>);
recipes.remove(<Botania:pool>);

//Other

recipes.remove(<cfm:ItemCoffeeTableWood>);

recipes.remove(<TwilightForest:tile.TFUncraftingTable>);

recipes.remove(<Forestry:resourceStorage:1>);

recipes.remove(<ForbiddenMagic:StarBlock>);

recipes.remove(<Genetics:misc:9>);

//Custom NPS

recipes.remove(<customnpcs:npcWand>);
recipes.remove(<customnpcs:npcAmethyst>);
recipes.remove(<customnpcs:npcRuby>);
recipes.remove(<customnpcs:npcSaphire>);

//Minecraft

recipes.remove(<minecraft:nether_star>);
recipes.remove(<minecraft:crafting_table>);

//BuildCraft

recipes.remove(<BuildCraft|Builders:machineBlock>);
recipes.remove(<BuildCraft|Silicon:laserTableBlock>);
recipes.remove(<BuildCraft|Silicon:laserBlock>);

//Immersive Engineering

recipes.remove(<ImmersiveEngineering:metal:30>);
recipes.remove(<ImmersiveEngineering:metal:32>);
recipes.remove(<ImmersiveEngineering:metal:33>);
recipes.remove(<ImmersiveEngineering:metal:36>);
recipes.remove(<ImmersiveEngineering:metal:38>);

//Compact Machines

recipes.remove(<CompactMachines:machine:5>);
recipes.remove(<CompactMachines:machine:4>);
recipes.remove(<CompactMachines:machine:3>);
recipes.remove(<CompactMachines:machine:2>);
recipes.remove(<CompactMachines:machine:1>);
recipes.remove(<CompactMachines:machine>);
recipes.remove(<CompactMachines:enlarger>);
recipes.remove(<CompactMachines:resizingcube>);
recipes.remove(<CompactMachines:interfaceitem>);
recipes.remove(<CompactMachines:shrinker>);

//Draconic Evolution

recipes.remove(<DraconicEvolution:draconicBoots>);
recipes.remove(<DraconicEvolution:draconicLeggs>);
recipes.remove(<DraconicEvolution:draconicChest>);
recipes.remove(<DraconicEvolution:draconicHelm>);
recipes.remove(<DraconicEvolution:draconicDistructionStaff>);
recipes.remove(<DraconicEvolution:draconicBow>);
recipes.remove(<DraconicEvolution:draconicSword>);
recipes.remove(<DraconicEvolution:draconicShovel>);
recipes.remove(<DraconicEvolution:draconicAxe>);
recipes.remove(<DraconicEvolution:draconicPickaxe>);
recipes.remove(<DraconicEvolution:magnet:1>);
recipes.remove(<DraconicEvolution:magnet>);
recipes.remove(<DraconicEvolution:grinder:3>);
recipes.remove(<DraconicEvolution:wyvernPickaxe>);
recipes.remove(<DraconicEvolution:wyvernShovel>);
recipes.remove(<DraconicEvolution:wyvernBow>);
recipes.remove(<DraconicEvolution:wyvernSword>);
recipes.remove(<DraconicEvolution:draconicCore>);
recipes.remove(<DraconicEvolution:draconiumEnergyCore:1>);
recipes.remove(<DraconicEvolution:draconiumEnergyCore>);
recipes.remove(<DraconicEvolution:wyvernCore>);
recipes.remove(<DraconicEvolution:wyvernBoots>);
recipes.remove(<DraconicEvolution:wyvernLeggs>);
recipes.remove(<DraconicEvolution:wyvernChest>);
recipes.remove(<DraconicEvolution:wyvernHelm>);
recipes.remove(<DraconicEvolution:draconicHoe>);
recipes.remove(<DraconicEvolution:chaoticCore>);
recipes.remove(<DraconicEvolution:awakenedCore>);
recipes.remove(<DraconicEvolution:draconiumChest>);

//Thaumcraft

recipes.remove(<Thaumcraft:ItemThaumonomicon>);
recipes.remove(<Thaumcraft:blockWoodenDevice:7>);
recipes.remove(<Thaumcraft:blockWoodenDevice:6>);

recipes.remove(<ThaumicTinkerer:shareBook>);

mods.thaumcraft.Arcane.removeRecipe(<ThaumicTinkerer:ichorPick>);
mods.thaumcraft.Arcane.removeRecipe(<ThaumicTinkerer:ichorShovel>);
mods.thaumcraft.Arcane.removeRecipe(<ThaumicTinkerer:ichorAxe>);
mods.thaumcraft.Arcane.removeRecipe(<ThaumicTinkerer:ichorSword>);
mods.thaumcraft.Arcane.removeRecipe(<ThaumicTinkerer:ichorclothHelm>);
mods.thaumcraft.Arcane.removeRecipe(<ThaumicTinkerer:ichorclothChest>);
mods.thaumcraft.Arcane.removeRecipe(<ThaumicTinkerer:ichorclothLegs>);
mods.thaumcraft.Arcane.removeRecipe(<ThaumicTinkerer:ichorclothBoots>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicTinkerer:ichorclothHelmGem>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicTinkerer:ichorclothChestGem>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicTinkerer:ichorclothLegsGem>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicTinkerer:ichorclothBootsGem>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicTinkerer:ichorPouch>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicTinkerer:ichorSwordGem>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicTinkerer:ichorPickGem>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicTinkerer:ichorAxeGem>);
mods.thaumcraft.Infusion.removeRecipe(<ThaumicTinkerer:ichorShovelGem>);
mods.thaumcraft.Infusion.removeRecipe(<thaumicenergistics:thaumicenergistics.block.advanced.infusion.provider>);

//Avaritia

recipes.remove(<Avaritia:Dire_Crafting>);
recipes.remove(<Avaritia:Resource:1>);
recipes.remove(<Avaritia:Crystal_Matrix>);
recipes.remove(<Avaritia:Resource>);
recipes.remove(<Avaritia:Neutron_Collector>);
recipes.remove(<Avaritia:Resource:9>);

recipes.remove(<avaritiaddons:ExtremeAutoCrafter>);
recipes.remove(<avaritiaddons:InfinityChest>);
recipes.remove(<avaritiaddons:CompressedChest>);

mods.avaritia.Compressor.remove(<Avaritia:Singularity>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:1>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:2>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:3>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:4>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:5>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:6>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:7>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:8>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:9>);
mods.avaritia.Compressor.remove(<Avaritia:Singularity:10>);
mods.avaritia.Compressor.remove(<denseneutroncollectors:Dense_Neutron_Collector>);
mods.avaritia.Compressor.remove(<denseneutroncollectors:Denser_Neutron_Collector>);
mods.avaritia.Compressor.remove(<denseneutroncollectors:Densest_Neutron_Collector>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Skull_Sword>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Neutron_Collector>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Neutronium_Compressor>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Resource:5>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Ultimate_Stew>);
mods.avaritia.ExtremeCrafting.remove(<appliedenergistics2:tile.BlockCreativeEnergyCell>);
mods.avaritia.ExtremeCrafting.remove(<ThermalExpansion:Cell>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Helm>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Chest>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Pants>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Shoes>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Pickaxe>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Sword>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Shovel>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Axe>);
mods.avaritia.ExtremeCrafting.remove(<Avaritia:Infinity_Bow>);
mods.avaritia.ExtremeCrafting.remove(<Botania:specialFlower>.withTag({type: "asgardandelion"}));
mods.avaritia.ExtremeCrafting.remove(<Avaritia:cluster_opener>);



// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.remove(<ExtraUtilities:creativebuilderswand>);
// ================================================================================
//#MARKER REMOVE SHAPED IC2 Crafting

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<Avaritia:Resource:1> * 9, [<Avaritia:Crystal_Matrix>]);
recipes.addShapeless(<StorageDrawers:upgradeCreative:1> * 2, [<ThermalExpansion:Strongbox>]);
recipes.addShapeless(<ExtraUtilities:angelRing:2>, [<ExtraUtilities:angelRing:*>, <ThermalFoundation:material:516>]);
recipes.addShapeless(<ExtraUtilities:angelRing:1>, [<ExtraUtilities:angelRing:*>, <AWWayofTime:aether>]);
recipes.addShapeless(<ExtraUtilities:angelRing:3>, [<ExtraUtilities:angelRing:*>, <DraconicEvolution:draconicIngot>]);
recipes.addShapeless(<ExtraUtilities:angelRing:4>, [<ExtraUtilities:angelRing:*>, <witchery:ingredient:165>]);
recipes.addShapeless(<ExtraUtilities:angelRing>, [<ExtraUtilities:angelRing:*>, <minecraft:feather>]);
recipes.addShapeless(<IC2:itemPlates:2>, [<ore:ingotBronze>, <ore:ingotBronze>, <ore:craftingToolForgeHammer>]);
recipes.addShapeless(<IC2:itemPlates:6>, [<ore:ingotLead>, <ore:ingotLead>, <ore:craftingToolForgeHammer>]);
recipes.addShapeless(<IC2:itemPlates:1>, [<ore:ingotTin>, <ore:ingotTin>, <ore:craftingToolForgeHammer>]);
recipes.addShapeless(<IC2:itemPlates>, [<ore:ingotCopper>, <ore:ingotCopper>, <ore:craftingToolForgeHammer>]);
recipes.addShapeless(<IC2:itemPlates:4>, [<ore:ingotIron>, <minecraft:iron_ingot>, <ore:craftingToolForgeHammer>]);
recipes.addShapeless(<IC2:itemPlates:3>, [<ore:ingotGold>, <ore:ingotGold>, <ore:craftingToolForgeHammer>]);
recipes.addShapeless(<Avaritia:Resource:7> * 8, [<ore:record>]);
recipes.addShapeless(<minecraft:crafting_table>, [<ore:stickWood>, <ore:itemFlint>, <ore:plankWood>, <ore:plankWood>]);
recipes.addShapeless(<minecraft:skull>, [<minecraft:arrow>, <minecraft:bone>, <minecraft:skull:2>]);
recipes.addShapeless(<ImmersiveEngineering:metal:30>, [<ImmersiveEngineering:tool>, <ore:ingotIron>, <ore:ingotIron>]);

// ================================================================================
//#MARKER ADD SHAPED

//Applied Energistics

recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:38>, [[<ore:crystalPureFluix>, <EnderIO:itemBasicCapacitor:2>, <ore:crystalPureFluix>], [<appliedenergistics2:item.ItemMultiMaterial:37>, <appliedenergistics2:item.ItemMultiMaterial:24>, <appliedenergistics2:item.ItemMultiMaterial:37>], [<ore:crystalPureFluix>, <appliedenergistics2:item.ItemMultiMaterial:37>, <ore:crystalPureFluix>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:37>, [[<ore:crystalPureFluix>, <EnderIO:itemBasicCapacitor:1>, <ore:crystalPureFluix>], [<appliedenergistics2:item.ItemMultiMaterial:36>, <appliedenergistics2:item.ItemMultiMaterial:24>, <appliedenergistics2:item.ItemMultiMaterial:36>], [<appliedenergistics2:item.ItemMultiMaterial:12>, <appliedenergistics2:item.ItemMultiMaterial:36>, <ore:crystalPureFluix>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:36>, [[<ore:crystalPureFluix>, <EnderIO:itemBasicCapacitor>, <ore:chipsetIron>], [<appliedenergistics2:item.ItemMultiMaterial:35>, <appliedenergistics2:item.ItemMultiMaterial:23>, <appliedenergistics2:item.ItemMultiMaterial:35>], [<ore:chipsetIron>, <appliedenergistics2:item.ItemMultiMaterial:35>, <ore:crystalPureFluix>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:35>, [[<appliedenergistics2:item.ItemMultiMaterial:12>, <EnderIO:itemBasicCapacitor>, <ore:chipsetRed>], [<appliedenergistics2:item.ItemMultiMaterial:10>, <appliedenergistics2:item.ItemMultiMaterial:22>, <appliedenergistics2:item.ItemMultiMaterial:10>], [<ore:chipsetRed>, <appliedenergistics2:item.ItemMultiMaterial:10>, <appliedenergistics2:item.ItemMultiMaterial:12>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockFluix>, [[<appliedenergistics2:item.ItemMultiMaterial:7>, <appliedenergistics2:item.ItemMultiMaterial:7>], [<appliedenergistics2:item.ItemMultiMaterial:7>, <appliedenergistics2:item.ItemMultiMaterial:7>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockCraftingUnit>, [[<appliedenergistics2:item.ItemMultiPart:76>, <TaintedMagic:ItemMaterial:5>, <appliedenergistics2:item.ItemMultiPart:76>], [<TaintedMagic:ItemMaterial>, <appliedenergistics2:item.ItemMultiMaterial:24>, <Thaumcraft:ItemResource:16>], [<AdvancedSolarPanel:asp_crafting_items:4>, <AWWayofTime:demonicSlate>, <AdvancedSolarPanel:asp_crafting_items:4>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockEnergyAcceptor>, [[<AdvancedSolarPanel:asp_crafting_items:8>, <ThermalExpansion:Glass:1>, <AdvancedSolarPanel:asp_crafting_items:8>], [<ThermalExpansion:Glass:1>, <AdvancedSolarPanel:asp_crafting_items:4>, <ThermalExpansion:Glass:1>], [<AdvancedSolarPanel:asp_crafting_items:8>, <ThermalExpansion:Glass:1>, <AdvancedSolarPanel:asp_crafting_items:8>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockDenseEnergyCell>, [[<appliedenergistics2:tile.BlockEnergyCell>, <appliedenergistics2:tile.BlockEnergyCell>, <appliedenergistics2:tile.BlockEnergyCell>], [<appliedenergistics2:tile.BlockEnergyCell>, <DraconicEvolution:draconicIngot>, <appliedenergistics2:tile.BlockEnergyCell>], [<appliedenergistics2:tile.BlockEnergyCell>, <appliedenergistics2:tile.BlockEnergyCell>, <appliedenergistics2:tile.BlockEnergyCell>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockEnergyCell>, [[<appliedenergistics2:item.ItemMultiMaterial:1>, <EnderIO:itemBasicCapacitor:2>, <DraconicEvolution:draconium>], [<appliedenergistics2:item.ItemMultiMaterial:9>, <EnderIO:blockIngotStorage:2>, <appliedenergistics2:item.ItemMultiMaterial:9>], [<DraconicEvolution:draconium>, <appliedenergistics2:item.ItemMultiMaterial:9>, <appliedenergistics2:item.ItemMultiMaterial:1>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockInscriber>, [[<EMT:EMTMachines>, <AdvancedSolarPanel:asp_crafting_items:4>, <Botania:storage:1>], [<IC2:blockElectric:2>, <EnderIO:itemMachinePart>, <ExtraUtilities:decorativeBlock1:5>], [<Botania:storage:1>, <AdvancedSolarPanel:asp_crafting_items:4>, <Thaumcraft:blockMetalDevice:3>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockDrive>, [[<IC2:itemPartIridium>, <appliedenergistics2:item.ItemMultiMaterial:24>, <IC2:itemPartIridium>], [<appliedenergistics2:item.ItemMultiPart:76>, <IronChest:BlockIronChest:8>, <appliedenergistics2:item.ItemMultiPart:76>], [<IC2:itemPartIridium>, <appliedenergistics2:item.ItemMultiMaterial:24>, <IC2:itemPartIridium>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockMolecularAssembler>, [[<Botania:storage>, <EnderIO:blockFusedQuartz:2>, <EnderIO:itemBasicCapacitor:2>], [<appliedenergistics2:item.ItemMultiMaterial:43>, <Avaritia:Triple_Craft>, <appliedenergistics2:item.ItemMultiMaterial:44>], [<EnderIO:itemBasicCapacitor:2>, <EnderIO:blockFusedQuartz:2>, <Botania:storage>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockCondenser>, [[<appliedenergistics2:tile.BlockFluix>, <appliedenergistics2:item.ItemMultiMaterial:38>, <appliedenergistics2:tile.BlockFluix>], [<appliedenergistics2:item.ItemMultiMaterial:38>, <IC2:blockMachine:14>, <appliedenergistics2:item.ItemMultiMaterial:38>], [<appliedenergistics2:tile.BlockFluix>, <appliedenergistics2:item.ItemMultiMaterial:38>, <appliedenergistics2:tile.BlockFluix>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockInterface>, [[<Botania:storage>, <EnderIO:blockFusedQuartz:2>, <EnderIO:itemBasicCapacitor:2>], [<appliedenergistics2:item.ItemMultiMaterial:43>, <AdvancedSolarPanel:asp_crafting_items:12>, <appliedenergistics2:item.ItemMultiMaterial:44>], [<EnderIO:itemBasicCapacitor:2>, <EnderIO:blockFusedQuartz:2>, <Botania:storage>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockQuartzGrowthAccelerator>, [[<IC2:upgradeModule>, <appliedenergistics2:item.ItemMultiPart:76>, <IC2:upgradeModule>], [<appliedenergistics2:tile.BlockQuartzGlass>, <appliedenergistics2:tile.BlockFluix>, <appliedenergistics2:tile.BlockQuartzGlass>], [<IC2:upgradeModule>, <appliedenergistics2:item.ItemMultiPart:76>, <IC2:upgradeModule>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockController>, [[<ore:compressedCobblestone4x>, <EnderIO:itemBasicCapacitor:2>, <ore:compressedCobblestone4x>], [<ore:circuitAdvanced>, <AdvancedSolarPanel:asp_crafting_items:4>, <ore:circuitAdvanced>], [<ore:compressedCobblestone4x>, <EnderIO:itemBasicCapacitor:2>, <ore:compressedCobblestone4x>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockCraftingUnit:1>, [[<AdvancedSolarPanel:asp_crafting_items:4>, <BigReactors:BRMetalBlock:4>, <AdvancedSolarPanel:asp_crafting_items:4>], [<BigReactors:BRMetalBlock:4>, <appliedenergistics2:tile.BlockCraftingUnit>, <BigReactors:BRMetalBlock:4>], [<Avaritia:Resource:1>, <BigReactors:BRMetalBlock:4>, <Avaritia:Resource:1>]]);

recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:60>, [[<Botania:storage:1>, <EnderIO:itemBasicCapacitor:2>, <Botania:storage:1>], [<appliedenergistics2:item.ItemMultiMaterial:59>, <EnderIO:itemFrankenSkull:2>, <appliedenergistics2:item.ItemMultiMaterial:59>], [<Botania:storage:1>, <appliedenergistics2:item.ItemMultiMaterial:59>, <Botania:storage:1>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:59>, [[<Botania:storage:1>, <EnderIO:itemBasicCapacitor:2>, <Botania:storage:1>], [<appliedenergistics2:item.ItemMultiMaterial:58>, <EnderIO:itemFrankenSkull:2>, <appliedenergistics2:item.ItemMultiMaterial:58>], [<Botania:storage:1>, <appliedenergistics2:item.ItemMultiMaterial:58>, <Botania:storage:1>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:58>, [[<appliedenergistics2:tile.BlockFluix>, <EnderIO:itemBasicCapacitor:2>, <appliedenergistics2:tile.BlockFluix>], [<appliedenergistics2:item.ItemMultiMaterial:57>, <EnderIO:itemFrankenSkull:2>, <appliedenergistics2:item.ItemMultiMaterial:57>], [<appliedenergistics2:tile.BlockFluix>, <appliedenergistics2:item.ItemMultiMaterial:57>, <appliedenergistics2:tile.BlockFluix>]]);
recipes.addShaped(<appliedenergistics2:item.ItemMultiMaterial:57>, [[<appliedenergistics2:tile.BlockFluix>, <EnderIO:itemBasicCapacitor:2>, <appliedenergistics2:tile.BlockFluix>], [<appliedenergistics2:item.ItemMultiMaterial:38>, <appliedenergistics2:item.ItemMultiMaterial:24>, <appliedenergistics2:item.ItemMultiMaterial:38>], [<appliedenergistics2:tile.BlockFluix>, <appliedenergistics2:item.ItemMultiMaterial:38>, <appliedenergistics2:tile.BlockFluix>]]);

recipes.addShaped(<ae2stuff:Wireless>, [[<appliedenergistics2:tile.BlockFluix>, <appliedenergistics2:item.ItemMultiMaterial:24>, <appliedenergistics2:tile.BlockFluix>], [<EnderIO:itemFrankenSkull:4>, <EnderIO:itemFrankenSkull:2>, <EnderIO:itemFrankenSkull:4>], [<appliedenergistics2:tile.BlockFluix>, <appliedenergistics2:item.ItemMultiMaterial:24>, <appliedenergistics2:tile.BlockFluix>]]);
recipes.addShaped(<ae2stuff:Inscriber>, [[<BuildCraft|Silicon:redstoneChipset:3>, <appliedenergistics2:tile.BlockInscriber>, <BuildCraft|Silicon:redstoneChipset:1>], [<appliedenergistics2:item.ItemMultiMaterial:24>, <EnderIO:itemBasicCapacitor:2>, <appliedenergistics2:item.ItemMultiMaterial:24>], [<BuildCraft|Silicon:redstoneChipset:1>, <appliedenergistics2:tile.BlockInscriber>, <BuildCraft|Silicon:redstoneChipset:3>]]);
recipes.addShaped(<ae2stuff:Grower>, [[<appliedenergistics2:tile.BlockQuartzGrowthAccelerator>, <EnderIO:itemBasicCapacitor:2>, <appliedenergistics2:tile.BlockQuartzGrowthAccelerator>], [<appliedenergistics2:tile.BlockQuartzGrowthAccelerator>, <IronChest:BlockIronChest:8>, <appliedenergistics2:tile.BlockQuartzGrowthAccelerator>], [<appliedenergistics2:tile.BlockQuartzGrowthAccelerator>, <ore:circuitAdvanced>, <appliedenergistics2:tile.BlockQuartzGrowthAccelerator>]]);

//MineFactoryReload

recipes.addShaped(<MineFactoryReloaded:machine.2>, [[<DraconicEvolution:draconicBlock>, <Avaritia:Crystal_Matrix>, <DraconicEvolution:draconicBlock>], [<Avaritia:Ultimate_Stew>, <ExtraUtilities:enderQuarry>, <Avaritia:Ultimate_Stew>], [<DraconicEvolution:draconicBlock>, <Avaritia:Crystal_Matrix>, <DraconicEvolution:draconicBlock>]]);
recipes.addShaped(<MineFactoryReloaded:plastic.sheet> * 2, [[<MineFactoryReloaded:plastic.raw>, <ThermalExpansion:material:513>, <MineFactoryReloaded:plastic.raw>], [<ThermalExpansion:material:513>, <EnderIO:bucketRocket_fuel>, <ThermalExpansion:material:513>], [<MineFactoryReloaded:plastic.raw>, <ThermalExpansion:material:513>, <MineFactoryReloaded:plastic.raw>]]);

//Extra Utilities

recipes.addShaped(<ExtraUtilities:peaceful_table_top>, [[<DraconicEvolution:draconicBlock>, <DraconicEvolution:wyvernSword>, <DraconicEvolution:draconicBlock>], [<ThermalFoundation:material:516>, <ExtraUtilities:generator.64:11>, <ThermalFoundation:material:516>], [<Avaritia:Resource_Block>, <customnpcs:npcDemonicIngot>, <Avaritia:Resource_Block>]]);
recipes.addShaped(<ExtraUtilities:golden_bag>, [[<customnpcs:npcOrb:4>, <AWWayofTime:blockCrystal>, <customnpcs:npcOrb:4>], [<ThaumicTinkerer:kamiResource>, <IronChest:BlockIronChest:8>, <ThaumicTinkerer:kamiResource>], [<customnpcs:npcOrb:4>, <AWWayofTime:blockCrystal>, <customnpcs:npcOrb:4>]]);
recipes.addShaped(<ExtraUtilities:drum:1>, [[<ExtraUtilities:bedrockiumIngot>, <ThermalExpansion:Tank:4>, <ExtraUtilities:bedrockiumIngot>], [<ExtraUtilities:bedrockiumIngot>, <ExtraUtilities:drum>, <ExtraUtilities:bedrockiumIngot>], [<ExtraUtilities:bedrockiumIngot>, <ThermalExpansion:Tank:4>, <ExtraUtilities:bedrockiumIngot>]]);
recipes.addShaped(<ExtraUtilities:drum>, [[<ore:ingotSteel>, <IC2:reactorPlatingExplosive>, <ore:ingotSteel>], [<ore:ingotSteel>, <ThermalExpansion:Tank:3>, <ore:ingotSteel>], [<ore:ingotSteel>, <IC2:reactorPlatingExplosive>, <ore:ingotSteel>]]);
recipes.addShaped(<ExtraUtilities:dark_portal>, [[<Avaritia:Resource:1>, <AdvancedSolarPanel:asp_crafting_items:13>, <Avaritia:Resource:1>], [<AdvancedSolarPanel:asp_crafting_items:13>, <Avaritia:Resource_Block>, <AdvancedSolarPanel:asp_crafting_items:13>], [<Avaritia:Resource:1>, <AdvancedSolarPanel:asp_crafting_items:13>, <Avaritia:Resource:1>]]);
recipes.addShaped(<ExtraUtilities:enderCollector>, [[<ore:pearlEnderEye>, <ore:blockEnderObsidian>, <ore:pearlEnderEye>], [null, <ore:blockEnderObsidian>, null], [<ore:blockEnderObsidian>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>]]);
recipes.addShaped(<ExtraUtilities:enderQuarryUpgrade:8>, [[<TaintedMagic:ItemThaumicDisassembler>, <TaintedMagic:ItemMaterial:10>, <TaintedMagic:ItemThaumicDisassembler>], [<Avaritia:Resource:1>, <ExtraUtilities:enderQuarryUpgrade:7>, <Avaritia:Resource:1>], [<divinerpg:divineStone>, <witchery:ingredient:83>, <divinerpg:divineStone>]]);
recipes.addShaped(<ExtraUtilities:enderQuarryUpgrade:7>, [[<ForbiddenMagic:MorphPickaxe>, <AdvancedSolarPanel:asp_crafting_items:4>, <ForbiddenMagic:MorphPickaxe>], [<divinerpg:divineStone>, <ExtraUtilities:enderQuarryUpgrade:6>, <divinerpg:divineStone>], [<divinerpg:bluefireStone>, <AdvancedSolarPanel:asp_crafting_items:4>, <divinerpg:bluefireStone>]]);
recipes.addShaped(<ExtraUtilities:enderQuarryUpgrade:6>, [[<TwilightForest:item.fieryIngot>, <Botania:elementiumPick>, <TwilightForest:item.fieryIngot>], [<Thaumcraft:ItemResource:16>, <ExtraUtilities:enderQuarryUpgrade>, <Thaumcraft:ItemResource:16>], [<TaintedMagic:ItemVoidsentBlood>, <witchery:ingredient:43>, <TaintedMagic:ItemVoidsentBlood>]]);
recipes.addShaped(<ExtraUtilities:bedrockiumIngot>, [[<ore:blockEmerald>, <ExtraUtilities:cobblestone_compressed:4>, <ore:blockEmerald>], [<ExtraUtilities:cobblestone_compressed:4>, <IC2:itemMOX>, <ExtraUtilities:cobblestone_compressed:4>], [<ore:blockEmerald>, <ExtraUtilities:cobblestone_compressed:4>, <ore:blockEmerald>]]);

//Avaritia

recipes.addShaped(<Avaritia:Resource:1>, [[<Avaritia:Resource>, <minecraft:nether_star>, <Avaritia:Resource>], [<Thaumcraft:ItemResource:16>, <AdvancedSolarPanel:asp_crafting_items:8>, <TaintedMagic:ItemMaterial>], [<Avaritia:Resource>, <minecraft:nether_star>, <Avaritia:Resource>]]);
recipes.addShaped(<Avaritia:Resource>, [[<divinerpg:moltenStone>, <ExtraUtilities:unstableingot:2>, <divinerpg:terranStone>], [<divinerpg:iceStone>, <ExtraUtilities:unstableingot:2>, <divinerpg:corruptedStone>], [<divinerpg:jungleStone>, <ExtraUtilities:unstableingot:2>, <divinerpg:enderStone>]]);
recipes.addShaped(<Avaritia:Crystal_Matrix>, [[<Avaritia:Resource:1>, <Avaritia:Resource:1>, <Avaritia:Resource:1>], [<Avaritia:Resource:1>, <customnpcs:npcDemonicIngot>, <Avaritia:Resource:1>], [<Avaritia:Resource:1>, <Avaritia:Resource:1>, <Avaritia:Resource:1>]]);


recipes.addShaped(<denseneutroncollectors:Densest_Neutron_Collector>, [[<denseneutroncollectors:Denser_Neutron_Collector>, <denseneutroncollectors:Denser_Neutron_Collector>, <denseneutroncollectors:Denser_Neutron_Collector>], [<denseneutroncollectors:Denser_Neutron_Collector>, <ExtraUtilities:pureLove>, <denseneutroncollectors:Denser_Neutron_Collector>], [<denseneutroncollectors:Denser_Neutron_Collector>, <denseneutroncollectors:Denser_Neutron_Collector>, <denseneutroncollectors:Denser_Neutron_Collector>]]);
recipes.addShaped(<denseneutroncollectors:Denser_Neutron_Collector>, [[<denseneutroncollectors:Dense_Neutron_Collector>, <denseneutroncollectors:Dense_Neutron_Collector>, <denseneutroncollectors:Dense_Neutron_Collector>], [<denseneutroncollectors:Dense_Neutron_Collector>, <Avaritia:Crystal_Matrix>, <denseneutroncollectors:Dense_Neutron_Collector>], [<denseneutroncollectors:Dense_Neutron_Collector>, <denseneutroncollectors:Dense_Neutron_Collector>, <denseneutroncollectors:Dense_Neutron_Collector>]]);
recipes.addShaped(<denseneutroncollectors:Dense_Neutron_Collector>, [[<Avaritia:Neutron_Collector>, <Avaritia:Neutron_Collector>, <Avaritia:Neutron_Collector>], [<Avaritia:Neutron_Collector>, <AdvancedSolarPanel:asp_crafting_items:13>, <Avaritia:Neutron_Collector>], [<Avaritia:Neutron_Collector>, <Avaritia:Neutron_Collector>, <Avaritia:Neutron_Collector>]]);

//Ender IO

recipes.addShaped(<EnderIO:blockTravelAnchor>, [[<IC2:itemBatLamaCrystal:*>, <AWWayofTime:blockCrystal>, <appliedenergistics2:item.ItemMultiMaterial:38>],
[<MineFactoryReloaded:meat.ingot.cooked>, <ThaumicTinkerer:warpGate>, <TwilightForest:item.fieryIngot>],
[<Avaritia:Resource:8>, <Avaritia:Resource_Block>, <TaintedMagic:ItemMaterial:5>]]);
recipes.addShaped(<EnderIO:blockPoweredSpawner>, [[<TaintedMagic:ItemMaterial>, <ExtraUtilities:decorativeBlock1:5>, <TaintedMagic:ItemMaterial>], [<EnderIO:itemFrankenSkull:4>, <ThermalExpansion:Frame:3>, <EnderIO:itemFrankenSkull:2>], [<DraconicEvolution:draconicIngot>, <EnderIO:itemBasicCapacitor:2>, <DraconicEvolution:draconicIngot>]]);
recipes.addShaped(<EnderIO:itemMachinePart>, [[<EnderIO:blockDarkIronBars>, <BuildCraft|Silicon:redstoneChipset:1>, <EnderIO:blockDarkIronBars>], [<BuildCraft|Silicon:redstoneChipset:1>, <EnderIO:itemBasicCapacitor>, <BuildCraft|Silicon:redstoneChipset:1>], [<EnderIO:blockDarkIronBars>, <BuildCraft|Silicon:redstoneChipset:1>, <EnderIO:blockDarkIronBars>]]);
recipes.addShaped(<EnderIO:itemBasicCapacitor:2>, [[null, <EnderIO:itemAlloy:2>, null], [<EnderIO:itemBasicCapacitor:1>, <minecraft:glowstone>, <EnderIO:itemBasicCapacitor:1>], [null, <EnderIO:itemAlloy:2>, null]]);
recipes.addShaped(<EnderIO:itemBasicCapacitor:1>, [[null, <EnderIO:itemBasicCapacitor>, null], [<ore:ingotEnergeticAlloy>, <ore:dustCoal>, <ore:ingotEnergeticAlloy>], [null, <EnderIO:itemBasicCapacitor>, null]]);
recipes.addShaped(<EnderIO:itemBasicCapacitor>, [[null, <ore:nuggetEnderium>, <ore:chipsetRed>], [<ore:nuggetEnderium>, <Forestry:thermionicTubes:7>, <ore:nuggetEnderium>], [<ore:chipsetRed>, <ore:nuggetEnderium>, null]]);

//ThermalExpansion

recipes.addShaped(<ThermalExpansion:Sponge>, [[<Avaritia:Resource:4>, <Avaritia:Resource:4>, <Avaritia:Resource:4>], [<ThermalExpansion:Sponge:1>, <Avaritia:Resource:5>, <ThermalExpansion:Sponge:2>], [<Avaritia:Resource:4>, <Avaritia:Resource:4>, <Avaritia:Resource:4>]]);
recipes.addShaped(<ThermalExpansion:Tesseract>, [[<DraconicEvolution:draconicIngot>, <ThermalFoundation:material:516>, <DraconicEvolution:draconicIngot>], [<ThermalFoundation:material:516>, <ThermalExpansion:Frame:11>, <ThermalFoundation:material:516>], [<DraconicEvolution:draconicIngot>, <ThermalFoundation:material:516>, <DraconicEvolution:draconicIngot>]]);
recipes.addShaped(<ThermalExpansion:satchel:3>, [[null, <ThermalFoundation:material:104>, null], [<ThermalExpansion:Glass:1>, <ThermalExpansion:satchel:2>, <ThermalExpansion:Glass:1>], [<ThermalFoundation:material:104>, null, <ThermalFoundation:material:104>]]);

//Draconic Evolution

recipes.addShaped(<DraconicEvolution:magnet:1>, [[<DraconicEvolution:draconium:2>, <DraconicEvolution:draconicBlock>, <DraconicEvolution:draconicBlock>], [null, null, <DraconicEvolution:magnet>], [<DraconicEvolution:draconium:2>, <DraconicEvolution:draconicBlock>, <DraconicEvolution:draconicBlock>]]);
recipes.addShaped(<DraconicEvolution:magnet>, [[<AWWayofTime:largeBloodStoneBrick>, <DraconicEvolution:draconium:2>, <DraconicEvolution:draconium:2>], [null, null, <MagicBees:magnet:16>], [<AWWayofTime:largeBloodStoneBrick>, <DraconicEvolution:draconium:2>, <DraconicEvolution:draconium:2>]]);
recipes.addShaped(<DraconicEvolution:grinder:3>, [[<ore:gaiaIngot>, <DraconicEvolution:draconium:2>, <ore:gaiaIngot>], [<TaintedMagic:ItemPrimordialEdge>, <DraconicEvolution:wyvernCore>, <Botania:terraSword>], [<ore:gaiaIngot>, <IC2:blockMachine:13>, <ore:gaiaIngot>]]);
recipes.addShaped(<DraconicEvolution:draconiumBlend>, [[<TwilightForest:item.steeleafIngot>, <ThaumicTinkerer:kamiResource:2>, <TwilightForest:item.steeleafIngot>], [<Botania:storage:1>, <TaintedMagic:BlockShadowmetal>, <ForbiddenMagic:StarBlock>], [<TwilightForest:item.steeleafIngot>, <BigReactors:BRMetalBlock:4>, <TwilightForest:item.steeleafIngot>]]);
recipes.addShaped(<DraconicEvolution:draconiumChest>, [[<DraconicEvolution:draconium>, <ThermalExpansion:Workbench:4>, <DraconicEvolution:draconium>], [<IronChest:BlockIronChest:8>, <DraconicEvolution:draconicCore>, <IronChest:BlockIronChest:8>], [<DraconicEvolution:draconium>, <EnderIO:blockAlloySmelter>, <DraconicEvolution:draconium>]]);

//Avaritia & addons

recipes.addShaped(<Avaritia:Dire_Crafting>, [[<Avaritia:Resource:1>, <ThaumicTinkerer:kamiResource:2>, <Avaritia:Resource:1>], [<AdvancedSolarPanel:asp_crafting_items:13>, <Avaritia:Triple_Craft>, <AdvancedSolarPanel:asp_crafting_items:13>], [<Avaritia:Resource:1>, <Botania:storage:1>, <Avaritia:Resource:1>]]);

recipes.addShaped(<avaritiaddons:InfinityChest>, [[<Avaritia:Resource:5>, <ore:blockCosmicNeutronium>, <Avaritia:Resource:5>], [<ore:ingotInfinity>, <avaritiaddons:CompressedChest>, <Avaritia:Resource:6>], [<Avaritia:Resource:5>, <ore:ingotInfinity>, <Avaritia:Resource:5>]]);

//IC2

recipes.addShaped(<IC2:blockMachine:14>, [[<AdvancedSolarPanel:asp_crafting_items:3>, <EnderIO:itemBasicCapacitor:2>, <AdvancedSolarPanel:asp_crafting_items:3>], [<IC2:itemBatLamaCrystal:26>, <IC2:blockMachine:12>, <IC2:itemBatLamaCrystal:26>], [<AdvancedSolarPanel:asp_crafting_items:3>, <EnderIO:itemBasicCapacitor:2>, <AdvancedSolarPanel:asp_crafting_items:3>]]);
recipes.addShaped(<IC2:blockMachine:2>, [[<ore:plateIron>, <ore:circuitBasic>, <ore:plateIron>], [<ore:chipsetRed>, <Thaumcraft:blockStoneDevice>, <BuildCraft|Silicon:redstoneChipset>]]);
recipes.addShaped(<IC2:blockMachine:5>, [[<ExtraUtilities:cobblestone_compressed:1>, <ore:circuitBasic>, <ExtraUtilities:cobblestone_compressed:1>], [<ExtraUtilities:cobblestone_compressed:1>, <IC2:blockMachine>, <ExtraUtilities:cobblestone_compressed:1>], [<ExtraUtilities:cobblestone_compressed:1>,  <EnderIO:itemBasicCapacitor>, <ExtraUtilities:cobblestone_compressed:1>]]);
recipes.addShaped(<IC2:blockMachine>, [[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], [<ore:plateIron>, <BuildCraft|Silicon:redstoneChipset>, <ore:plateIron>], [<ore:plateIron>, <ore:plateIron>, <ore:plateIron>]]);
recipes.addShaped(<IC2:blockMachine:3>, [[<ore:itemSilicon>, <EnderIO:itemBasicCapacitor>, <ore:itemSilicon>], [<ore:compressedCobblestone2x>, <IC2:blockMachine>, <ore:compressedCobblestone2x>], [<appliedenergistics2:tile.BlockGrinder>, <ore:circuitBasic>, <appliedenergistics2:tile.BlockGrinder>]]);
recipes.addShaped(<IC2:itemToolForgeHammer>, [[<Botania:manaResource:7>, <ore:ingotSteel>, null], [<ore:ingotSteel>, <ore:treatedStick>, <ore:treatedStick>], [<Botania:manaResource:7>, <ore:ingotSteel>, null]]);
recipes.addShaped(<IC2:itemPartCircuitAdv>, [[<ore:chipsetRed>, <Genetics:misc:9>, <ore:chipsetRed>], [<ore:circuitBasic>, <ore:redstoneCrystal>, <ore:circuitBasic>], [<ore:chipsetRed>, <Genetics:misc:9>, <ore:chipsetRed>]]);
recipes.addShaped(<IC2:itemPartCircuit>, [[<IC2:itemCable>, <IC2:itemCable>, <IC2:itemCable>], [<EnderIO:itemBasicCapacitor>, <IC2:itemPlates:4>, <EnderIO:itemBasicCapacitor>], [<IC2:itemCable>, <IC2:itemCable>, <IC2:itemCable>]]);
recipes.addShaped(<GraviSuite:itemSimpleItem:6>, [[<minecraft:glowstone_dust>, <IC2:itemPartAlloy>, <minecraft:glowstone_dust>], [<IC2:itemPartCircuitAdv>, <IC2:upgradeModule>, <IC2:itemPartCircuitAdv>], [<IC2:itemPartAlloy>, <IC2:reactorVentDiamond:*>, <IC2:itemPartAlloy>]]);
recipes.addShaped(<AdvancedSolarPanel:BlockAdvSolarPanel:1>, [[<IC2:itemPartCarbonPlate>, <minecraft:lapis_block>, <IC2:itemPartCarbonPlate>], [<IC2:itemPartIridium>, <AdvancedSolarPanel:BlockAdvSolarPanel>, <IC2:itemPartIridium>], [<IC2:itemPartCircuitAdv>, <AdvancedSolarPanel:asp_crafting_items:3>, <IC2:itemPartCircuitAdv>]]);

//Advanced Solar Panel

recipes.addShaped(<AdvancedSolarPanel:BlockMolecularTransformer>, [[<IC2:blockMachine:12>, <IC2:blockElectric:2>, <EnderIO:itemBasicCapacitor:2>], [<IC2:itemPartCircuitAdv>, <AdvancedSolarPanel:asp_crafting_items:12>, <IC2:itemPartCircuitAdv>], [<EnderIO:itemBasicCapacitor:2>, <IC2:blockElectric:2>, <IC2:blockMachine:12>]]);
recipes.addShaped(<AdvancedSolarPanel:asp_crafting_items:13>, [[<AdvancedSolarPanel:asp_crafting_items:4>, <minecraft:nether_star>, <AdvancedSolarPanel:asp_crafting_items:4>], [<minecraft:nether_star>, <IC2:itemCellEmpty:3>, <minecraft:nether_star>], [<AdvancedSolarPanel:asp_crafting_items:4>, <minecraft:nether_star>, <AdvancedSolarPanel:asp_crafting_items:4>]]);
recipes.addShaped(<AdvancedSolarPanel:asp_crafting_items:12>, [[<AdvancedSolarPanel:asp_crafting_items:5>, <IC2:reactorReflectorThick:1>, <AdvancedSolarPanel:asp_crafting_items:5>], [<AdvancedSolarPanel:asp_crafting_items:5>, null, <AdvancedSolarPanel:asp_crafting_items:5>], [<AdvancedSolarPanel:asp_crafting_items:5>, <IC2:reactorReflectorThick:1>, <AdvancedSolarPanel:asp_crafting_items:5>]]);

//Iron Chest


    //Chest recipes
recipes.addShaped(<IronChest:BlockIronChest>, [[<IC2:itemDensePlates:4>, <ore:plateIron>, <ore:plateDenseIron>], [<ore:plateIron>, <IronChest:BlockIronChest:3>, <ore:plateIron>], [<IC2:itemDensePlates:4>, <ore:plateIron>, <ore:plateDenseIron>]]);
recipes.addShaped(<IronChest:BlockIronChest:1>, [[<ore:plateDenseGold>, <ore:plateGold>, <IC2:itemDensePlates:3>], [<ore:plateGold>, <IronChest:BlockIronChest:4>, <IC2:itemPlates:3>], [<ore:plateDenseGold>, <ore:plateGold>, <ore:plateDenseGold>]]);
recipes.addShaped(<IronChest:BlockIronChest:2>, [[<Botania:manaResource:2>, <Botania:manaResource:2>, <Botania:manaResource:2>], [<Botania:manaResource:2>, <IronChest:BlockIronChest:1>, <Botania:manaResource:2>], [<Botania:manaResource:2>, <Botania:manaResource:2>, <Botania:manaResource:2>]]);
recipes.addShaped(<IronChest:BlockIronChest:4>, [[<ore:ingotSteel>, <BuildCraft|Silicon:redstoneChipset>, <IC2:itemIngot:3>], [<BuildCraft|Silicon:redstoneChipset>, <IronChest:BlockIronChest>, <BuildCraft|Silicon:redstoneChipset>], [<IC2:itemIngot:3>, <BuildCraft|Silicon:redstoneChipset>, <IC2:itemIngot:3>]]);
recipes.addShaped(<IronChest:BlockIronChest:5>, [[<appliedenergistics2:tile.BlockQuartzGlass>, <appliedenergistics2:tile.BlockQuartzGlass>, <appliedenergistics2:tile.BlockQuartzGlass>], [<Botania:manaResource:9>, <IronChest:BlockIronChest:2>, <Botania:manaResource:9>], [<appliedenergistics2:tile.BlockQuartzGlass>, <appliedenergistics2:tile.BlockQuartzGlass>, <appliedenergistics2:tile.BlockQuartzGlass>]]);
recipes.addShaped(<IronChest:BlockIronChest:6>, [[<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>], [<ExtraUtilities:decorativeBlock1:1>, <IronChest:BlockIronChest:5>, <ExtraUtilities:decorativeBlock1:1>], [<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>]]);
recipes.addShaped(<IronChest:BlockIronChest:8>, [[<etfuturum:netherite_ingot>, <BuildCraft|Silicon:redstoneChipset:7>, <etfuturum:netherite_ingot>], [<IC2:itemDensePlates:5>, <IronChest:BlockIronChest:6>, <IC2:itemDensePlates:5>], [<etfuturum:netherite_ingot>, <BuildCraft|Silicon:redstoneChipset:7>, <etfuturum:netherite_ingot>]]);

    //Chest upgrade recipes
recipes.addShaped(<IronChest:copperIronUpgrade>, [[<IC2:itemDensePlates:4>, <ore:plateIron>, <ore:plateDenseIron>], [<ore:plateIron>, <ore:ingotCopper>, <ore:plateIron>], [<IC2:itemDensePlates:4>, <ore:plateIron>, <ore:plateDenseIron>]]);
recipes.addShaped(<IronChest:ironSteelUpgrade>, [[<ore:ingotSteel>, <BuildCraft|Silicon:redstoneChipset>, <IC2:itemIngot:3>], [<BuildCraft|Silicon:redstoneChipset>, <ore:ingotIron>, <BuildCraft|Silicon:redstoneChipset>], [<IC2:itemIngot:3>, <BuildCraft|Silicon:redstoneChipset>, <IC2:itemIngot:3>]]);
recipes.addShaped(<IronChest:steelGoldUpgrade>, [[<ore:plateDenseGold>, <ore:plateGold>, <IC2:itemDensePlates:3>], [<ore:plateGold>, <ore:ingotSteel>, <IC2:itemPlates:3>], [<ore:plateDenseGold>, <ore:plateGold>, <ore:plateDenseGold>]]);
recipes.addShaped(<IronChest:goldDiamondUpgrade>, [[<Botania:manaResource:2>, <Botania:manaResource:2>, <Botania:manaResource:2>], [<Botania:manaResource:2>, <ore:ingotGold>, <Botania:manaResource:2>], [<Botania:manaResource:2>, <Botania:manaResource:2>, <Botania:manaResource:2>]]);
recipes.addShaped(<IronChest:diamondCrystalUpgrade>, [[<appliedenergistics2:tile.BlockQuartzGlass>, <appliedenergistics2:tile.BlockQuartzGlass>, <appliedenergistics2:tile.BlockQuartzGlass>], [<Botania:manaResource:9>, <Botania:manaResource:2>, <Botania:manaResource:9>], [<appliedenergistics2:tile.BlockQuartzGlass>, <appliedenergistics2:tile.BlockQuartzGlass>, <appliedenergistics2:tile.BlockQuartzGlass>]]);
recipes.addShaped(<IronChest:diamondObsidianUpgrade>, [[<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>], [<ExtraUtilities:decorativeBlock1:1>, <IronChest:diamondCrystalUpgrade>, <ExtraUtilities:decorativeBlock1:1>], [<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>]]);
recipes.addShaped(<IronChest:obsidianNetheriteUpgrade>, [[<etfuturum:netherite_ingot>, <BuildCraft|Silicon:redstoneChipset:7>, <etfuturum:netherite_ingot>], [<IC2:itemDensePlates:5>, <ExtraUtilities:decorativeBlock1:1>, <IC2:itemDensePlates:5>], [<etfuturum:netherite_ingot>, <BuildCraft|Silicon:redstoneChipset:7>, <etfuturum:netherite_ingot>]]);

    //Barrel recipes
recipes.addShaped(<etfuturum:copper_barrel>, [[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:ingotCopper>, <etfuturum:barrel>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>]]);
recipes.addShaped(<etfuturum:iron_barrel>, [[<IC2:itemDensePlates:4>, <ore:plateIron>, <ore:plateDenseIron>], [<ore:plateIron>, <etfuturum:copper_barrel>, <ore:plateIron>], [<IC2:itemDensePlates:4>, <ore:plateIron>, <ore:plateDenseIron>]]);
recipes.addShaped(<etfuturum:steel_barrel>, [[<ore:ingotSteel>, <BuildCraft|Silicon:redstoneChipset>, <IC2:itemIngot:3>], [<BuildCraft|Silicon:redstoneChipset>, <etfuturum:iron_barrel>, <BuildCraft|Silicon:redstoneChipset>], [<IC2:itemIngot:3>, <BuildCraft|Silicon:redstoneChipset>, <IC2:itemIngot:3>]]);
recipes.addShaped(<etfuturum:gold_barrel>, [[<ore:plateDenseGold>, <ore:plateGold>, <IC2:itemDensePlates:3>], [<ore:plateGold>, <etfuturum:steel_barrel>, <IC2:itemPlates:3>], [<ore:plateDenseGold>, <ore:plateGold>, <ore:plateDenseGold>]]);
recipes.addShaped(<etfuturum:diamond_barrel>, [[<Botania:manaResource:2>, <Botania:manaResource:2>, <Botania:manaResource:2>], [<Botania:manaResource:2>, <etfuturum:gold_barrel>, <Botania:manaResource:2>], [<Botania:manaResource:2>, <Botania:manaResource:2>, <Botania:manaResource:2>]]);
recipes.addShaped(<etfuturum:obsidian_barrel>, [[<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>], [<Botania:manaResource:9>, <etfuturum:diamond_barrel>, <Botania:manaResource:9>], [<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>]]);
recipes.addShaped(<etfuturum:netherite_barrel>, [[<etfuturum:netherite_ingot>, <BuildCraft|Silicon:redstoneChipset:7>, <etfuturum:netherite_ingot>], [<IC2:itemDensePlates:5>, <etfuturum:obsidian_barrel>, <IC2:itemDensePlates:5>], [<etfuturum:netherite_ingot>, <BuildCraft|Silicon:redstoneChipset:7>, <etfuturum:netherite_ingot>]]);
recipes.addShaped(<etfuturum:darksteel_barrel>, [[<EnderIO:blockIngotStorage:6>, <BuildCraft|Silicon:redstoneChipset:7>, <EnderIO:itemAlloy:6>], [<IC2:itemDensePlates:5>, <etfuturum:obsidian_barrel>, <IC2:itemDensePlates:5>], [<EnderIO:itemAlloy:6>, <BuildCraft|Silicon:redstoneChipset:7>, <EnderIO:blockIngotStorage:6>]]);

    //Barrel upgrade recipes
recipes.addShaped(<etfuturum:barrel_upgrade:1>, [[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:plankWood>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>]]);
recipes.addShaped(<etfuturum:barrel_upgrade:8>, [[<IC2:itemDensePlates:4>, <ore:plateIron>, <ore:plateDenseIron>], [<ore:plateIron>, <ore:ingotCopper>, <ore:plateIron>], [<IC2:itemDensePlates:4>, <ore:plateIron>, <ore:plateDenseIron>]]);
recipes.addShaped(<etfuturum:barrel_upgrade:4>, [[<ore:plateDenseGold>, <ore:plateGold>, <IC2:itemDensePlates:3>], [<ore:plateGold>, <ore:ingotSteel>, <IC2:itemPlates:3>], [<ore:plateDenseGold>, <ore:plateGold>, <ore:plateDenseGold>]]);
recipes.addShaped(<etfuturum:barrel_upgrade:3>, [[<Botania:manaResource:2>, <Botania:manaResource:2>, <Botania:manaResource:2>], [<Botania:manaResource:2>, <ore:ingotGold>, <Botania:manaResource:2>], [<Botania:manaResource:2>, <Botania:manaResource:2>, <Botania:manaResource:2>]]);
recipes.addShaped(<etfuturum:barrel_upgrade:5>, [[<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>], [<Botania:manaResource:9>, <Botania:manaResource:2>, <Botania:manaResource:9>], [<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:1>]]);
recipes.addShaped(<etfuturum:barrel_upgrade:6>, [[<etfuturum:netherite_ingot>, <BuildCraft|Silicon:redstoneChipset:7>, <etfuturum:netherite_ingot>], [<IC2:itemDensePlates:5>, <ExtraUtilities:decorativeBlock1:1>, <IC2:itemDensePlates:5>], [<etfuturum:netherite_ingot>, <BuildCraft|Silicon:redstoneChipset:7>, <etfuturum:netherite_ingot>]]);
recipes.addShaped(<etfuturum:barrel_upgrade:7>, [[<EnderIO:blockIngotStorage:6>, <BuildCraft|Silicon:redstoneChipset:7>, <EnderIO:itemAlloy:6>], [<IC2:itemDensePlates:5>, <ExtraUtilities:decorativeBlock1:1>, <IC2:itemDensePlates:5>], [<EnderIO:itemAlloy:6>, <BuildCraft|Silicon:redstoneChipset:7>, <EnderIO:blockIngotStorage:6>]]);

//Big Reactors

recipes.addShaped(<BigReactors:BRReactorPart:1>, [[<BigReactors:BRReactorPart>, <BigReactors:BRMetalBlock>, <BigReactors:BRReactorPart>], [<EnderIO:blockIngotStorage:2>, <AdvancedSolarPanel:asp_crafting_items:13>, <EnderIO:blockIngotStorage:2>], [<BigReactors:BRReactorPart>, <EnderIO:blockIngotStorage>, <BigReactors:BRReactorPart>]]);
recipes.addShaped(<BigReactors:BRReactorPart:2>, [[<BigReactors:BRReactorPart>, <IC2:itemPartIridium>, <BigReactors:BRReactorPart>], [<EnderIO:blockIngotStorage:2>, <BigReactors:BRMetalBlock>, <EnderIO:blockIngotStorage:2>], [<BigReactors:BRReactorPart>, <BigReactors:BRMetalBlock>, <BigReactors:BRReactorPart>]]);
recipes.addShaped(<BigReactors:BRReactorPart> * 8, [[<EnderIO:blockIngotStorage:6>, <BigReactors:BRMetalBlock:2>, <EnderIO:blockIngotStorage:6>], [<BigReactors:BRMetalBlock:2>, <BigReactors:BRMetalBlock>, <BigReactors:BRMetalBlock:2>], [<EnderIO:blockIngotStorage:6>, <BigReactors:BRMetalBlock:2>, <EnderIO:blockIngotStorage:6>]]);
recipes.addShaped(<BigReactors:BRReactorPart:3>, [[<BigReactors:BRReactorPart>, <BigReactors:BRMetalBlock>, <BigReactors:BRReactorPart>], [<EnderIO:blockIngotStorage:1>, <AdvancedSolarPanel:asp_crafting_items:4>, <EnderIO:blockIngotStorage:1>], [<BigReactors:BRReactorPart>, <ore:blockDarkSteel>, <BigReactors:BRReactorPart>]]);
recipes.addShaped(<BigReactors:YelloriumFuelRod>, [[<EnderIO:itemAlloy>, <BigReactors:BRIngot:2>, <EnderIO:itemAlloy>], [<EnderIO:itemAlloy>, <IC2:itemRTGPellet>, <EnderIO:itemAlloy>], [<EnderIO:itemAlloy>, <BigReactors:BRIngot:2>, <EnderIO:itemAlloy>]]);

//Immersive Engineering

recipes.addShaped(<ImmersiveEngineering:metal:33>, [[<ImmersiveEngineering:tool>, <ore:ingotLead>], [<ore:ingotLead>, null]]);
recipes.addShaped(<ImmersiveEngineering:metal:36>, [[<ImmersiveEngineering:tool>, <ImmersiveEngineering:metal:5>], [<ImmersiveEngineering:metal:5>, null]]);
recipes.addShaped(<ImmersiveEngineering:metal:32>, [[<ImmersiveEngineering:tool>, <ore:ingotAluminum>], [<ore:ingotAluminum>, null]]);
recipes.addShaped(<ImmersiveEngineering:metal:38>, [[<ImmersiveEngineering:tool>, <ore:ingotSteel>], [<ore:ingotSteel>, null]]);

//Compact Machines

recipes.addShaped(<CompactMachines:machine:5>, [[<Avaritia:Resource_Block>, <customnpcs:npcOrb:3>, <Avaritia:Resource_Block>], [<customnpcs:npcOrb:3>, <CompactMachines:machine:4>, <customnpcs:npcOrb:3>], [<Avaritia:Resource_Block>, <customnpcs:npcOrb:3>, <Avaritia:Resource_Block>]]);
recipes.addShaped(<CompactMachines:machine:4>, [[<Avaritia:Resource:4>, <customnpcs:npcOrb:9>, <Avaritia:Resource:4>], [<customnpcs:npcOrb:9>, <DraconicEvolution:draconiumEnergyCore>, <customnpcs:npcOrb:9>], [<Avaritia:Resource:4>, <customnpcs:npcOrb:9>, <Avaritia:Resource:4>]]);
recipes.addShaped(<CompactMachines:machine:3>, [[<Avaritia:Resource:3>, <customnpcs:npcOrb:15>, <Avaritia:Resource:3>], [<customnpcs:npcOrb:15>, <CompactMachines:machine:2>, <customnpcs:npcOrb:15>], [<Avaritia:Resource:3>, <customnpcs:npcOrb:15>, <Avaritia:Resource:3>]]);
recipes.addShaped(<CompactMachines:machine:2>, [[<Avaritia:Resource:3>, <customnpcs:npcOrb:4>, <Avaritia:Resource:3>], [<customnpcs:npcOrb:4>, <DraconicEvolution:wyvernCore>, <customnpcs:npcOrb:4>], [<Avaritia:Resource:3>, <customnpcs:npcOrb:4>, <Avaritia:Resource:3>]]);
recipes.addShaped(<CompactMachines:machine:1>, [[<Avaritia:Resource:2>, <ore:blockIron>, <Avaritia:Resource:2>], [<ore:blockIron>, <CompactMachines:machine>, <ore:blockIron>], [<Avaritia:Resource:2>, <minecraft:iron_block>, <Avaritia:Resource:2>]]);
recipes.addShaped(<CompactMachines:machine>, [[<Avaritia:Resource:2>, <ore:plankWood>, <Avaritia:Resource:2>], [<ore:plankWood>, <DraconicEvolution:draconicCore>, <ore:plankWood>], [<Avaritia:Resource:2>, <ore:plankWood>, <Avaritia:Resource:2>]]);

//Other

recipes.addShapeless(<IC2:itemArmorQuantumChestplate:1>, [<EMT:itemArmorQuantumChestplate:*>, <ThaumicTinkerer:spellCloth:*>]);
recipes.addShaped(<cfm:ItemCoffeeTableWood>, [[<minecraft:log>, <minecraft:log>, <minecraft:log>], [<minecraft:planks>, null, <minecraft:planks>]]);

recipes.addShaped(<StorageDrawers:upgradeCreative> * 2, [[<ore:woodStick>, <StorageDrawers:upgrade:6>, <ore:woodStick>], [<StorageDrawers:upgrade:6>, <ThermalExpansion:Cache>, <StorageDrawers:upgrade:6>], [<ore:woodStick>, <StorageDrawers:upgrade:6>, <ore:woodStick>]]);

recipes.addShaped(<witchery:ingredient:96> * 3, [[<witchery:ingredient:100>, <witchery:spanishmoss>], [<witchery:ingredient:69>, <witchery:glintweed>], [<witchery:ingredient:22>, <witchery:ingredient:24>]]);
recipes.addShaped(<witchery:ingredient:100>, [[null, <witchery:ingredient:148>, null], [<witchery:ingredient:148>, <minecraft:string>, <witchery:ingredient:148>], [null, <witchery:ingredient:148>, null]]);
recipes.addShaped(<witchery:ingredient:150>, [[<witchery:ingredient:149>, <witchery:ingredient:149>, <witchery:ingredient:149>], [<witchery:ingredient:149>, <Avaritia:Resource:4>, <witchery:ingredient:149>], [<witchery:ingredient:149>, <witchery:ingredient:149>, <witchery:ingredient:149>]]);
recipes.addShaped(<witchery:ingredient:149>, [[<witchery:ingredient:148>, <witchery:ingredient:148>, <witchery:ingredient:148>], [<witchery:ingredient:148>, <Avaritia:Resource:3>, <witchery:ingredient:148>], [<witchery:ingredient:148>, <witchery:ingredient:148>, <witchery:ingredient:148>]]);

recipes.addShaped(<Genetics:misc:9>, [[<minecraft:lapis_block>, <TwilightForest:item.ironwoodIngot>, <minecraft:glowstone>], [<BuildCraft|Silicon:redstoneChipset:7>, <Forestry:chipsets:1>, <BuildCraft|Silicon:redstoneChipset:7>], [<minecraft:glowstone>, <TwilightForest:item.ironwoodIngot>, <minecraft:lapis_block>]]);

recipes.addShaped(<minecraft:crafting_table>, [[<ore:stickWood>, <ore:itemFlint>], [<ore:plankWood>, <ore:plankWood>]]);

recipes.addShaped(<simplyjetpacks:jetpacksCommon:9001>, [[<AWWayofTime:blockCrystal>, <simplyjetpacks:fluxpacksCommon:9001>, <AWWayofTime:blockCrystal>], [<AWWayofTime:blockCrystal>, <ExtraUtilities:angelRing:2>, <AWWayofTime:blockCrystal>], [<AWWayofTime:bloodMagicBaseItems:27>, null, <AWWayofTime:bloodMagicBaseItems:27>]]);
recipes.addShaped(<simplyjetpacks:fluxpacksCommon:9001>, [[<Avaritia:Resource:1>, <ThermalExpansion:Cell>, <Avaritia:Resource:1>], [<Avaritia:Resource:1>, <simplyjetpacks:components>, <Avaritia:Resource:1>]]);

recipes.addShaped(<SolarExpansion:solarCoreAdvanced>, [[null, <witchery:ingredient:150>, null], [<witchery:ingredient:150>, <SolarExpansion:solarCoreResonant>, <witchery:ingredient:150>], [null, <witchery:ingredient:150>, null]]);
recipes.addShaped(<SolarExpansion:solarCoreUltimate>, [[null, <ThermalFoundation:material:516>, null], [<ThermalFoundation:material:516>, <SolarExpansion:solarCoreAdvanced>, <ThermalFoundation:material:516>], [null, <ThermalFoundation:material:516>, null]]);

recipes.addShaped(<BuildCraft|Builders:machineBlock>, [[<DraconicEvolution:draconium:2>, <EnderIO:itemBasicCapacitor:2>, <DraconicEvolution:draconium:2>], [<IC2:itemPartCircuitAdv>, <ThermalFoundation:material:140>, <IC2:itemPartCircuitAdv>], [<Botania:storage:1>, <divinerpg:divinePickaxe>, <Botania:storage:1>]]);
recipes.addShaped(<BuildCraft|Silicon:laserTableBlock>, [[<ExtraUtilities:decorativeBlock1:1>, <minecraft:diamond>, <ExtraUtilities:decorativeBlock1:1>], [<ExtraUtilities:decorativeBlock1:1>, <minecraft:redstone>, <ExtraUtilities:decorativeBlock1:1>], [<ExtraUtilities:decorativeBlock1:1>, <BuildCraft|Core:diamondGearItem>, <ExtraUtilities:decorativeBlock1:1>]]);
recipes.addShaped(<BuildCraft|Silicon:laserBlock>, [[<ExtraUtilities:decorativeBlock1:1>, <minecraft:redstone>, <minecraft:redstone>], [<BuildCraft|Core:diamondGearItem>, <BuildCraft|Core:diamondGearItem>, <minecraft:redstone>], [<ExtraUtilities:decorativeBlock1:1>, <minecraft:redstone>, <minecraft:redstone>]]);

recipes.addShaped(<Railcraft:machine.alpha:2>, [[<ore:blockEmerald>, <appliedenergistics2:tile.BlockSkyStone:1>, <ore:blockEmerald>], [<minecraft:obsidian>, <appliedenergistics2:item.ItemMultiMaterial:9>, <minecraft:obsidian>], [<minecraft:emerald_block>, <appliedenergistics2:tile.BlockSkyStone:1>, <ore:blockEmerald>]]);



//Avaritia compressor

mods.avaritia.Compressor.add(<AdvancedSolarPanel:BlockAdvSolarPanel:4>, 128, <AdvancedSolarPanel:BlockAdvSolarPanel:3>);
mods.avaritia.Compressor.add(<Avaritia:Singularity>, 12250, <minecraft:iron_block>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:1>, 12250, <minecraft:gold_block>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:2>, 12250, <minecraft:lapis_block>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:3>, 12250, <minecraft:redstone_block>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:4>, 12250, <minecraft:quartz_block>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:5>, 12250, <ore:blockCopper>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:6>, 12250, <ore:blockTin>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:7>, 12250, <ore:blockLead>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:8>, 12250, <ore:blockSilver>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:9>, 12250, <ore:blockNickel>);
mods.avaritia.Compressor.add(<Avaritia:Singularity:11>, 666, <minecraft:clay>);
mods.avaritia.Compressor.add(<ExtraTrees:food:23>, 256, <ExtraTrees:food:22>);
mods.avaritia.Compressor.add(<ExtraTrees:food:40>, 666, <Forestry:fruits:6>);
mods.avaritia.Compressor.add(<customnpcs:npcOrb:14> * 4, 9000, <minecraft:redstone>);
mods.avaritia.Compressor.add(<customnpcs:npcOrb:2>, 256, <ExtraUtilities:pureLove>);
mods.avaritia.Compressor.add(<customnpcs:npcOrb:4> * 4, 9000, <minecraft:gold_ingot>);
mods.avaritia.Compressor.add(<customnpcs:npcOrb:8> * 4, 9000, <minecraft:iron_ingot>);
mods.avaritia.Compressor.add(<customnpcs:npcOrb:5>, 256, <Botania:storage:1>);
mods.avaritia.Compressor.add(<customnpcs:npcOrb> * 4, 4000, <minecraft:quartz>);
mods.avaritia.Compressor.add(<customnpcs:npcOrb:15>, 1000, <minecraft:obsidian>);
mods.avaritia.Compressor.add(<customnpcs:npcOrb:3> * 4, 9000, <minecraft:diamond>);
mods.avaritia.Compressor.add(<customnpcs:npcOrb:9> * 4, 9000, <BigReactors:BRIngot:1>);
recipes.addShapeless(<customnpcs:npcOrb:10>, [<ThermalExpansion:Cell>.reuse()]);

//Tconstruct

recipes.addShaped(<TConstruct:heartCanister:6>, [[<divinerpg:furyFire>, <ThaumicTinkerer:kamiResource>], [<TConstruct:heartCanister:5>, <TConstruct:heartCanister:4>]]);
recipes.addShaped(<TConstruct:heartCanister:5>, [[<AWWayofTime:bloodMagicBaseItems:27>, <divinerpg:jungleStone>], [<Avaritia:Resource:4>, <TConstruct:heartCanister:3>]]);

mods.tconstruct.Casting.addBasinRecipe(<ThermalFoundation:Storage:6>, <liquid:molten.bedrockiumingots> * 1440, <DraconicEvolution:draconiumBlend>, true, 20);
mods.tconstruct.Casting.addTableRecipe(<ThermalFoundation:material:516>, <liquid:mana> * 256, <ThermalFoundation:material:38>, true, 8);
mods.tconstruct.Casting.addBasinRecipe(<ExtraUtilities:pureLove>, <liquid:mana> * 72000, <DraconicEvolution:draconicBlock>, true, 20);
mods.tconstruct.Smeltery.addAlloy(<liquid:mana> * 512, [<liquid:ic2uumatter> * 4000, <liquid:xpjuice> * 3072, <liquid:mithril.molten> * 1296, <liquid:binnie.dna.raw> * 1024]);
mods.tconstruct.Casting.removeBasinRecipe(<ThermalExpansion:Glass>);

//Extra utilities + ThermalExpansion

mods.extraUtils.QED.addShapedRecipe(<EnderIO:blockTransceiver>, [[<EnderIO:itemAlloy>, <EnderIO:itemFrankenSkull:3>, <EnderIO:itemAlloy>],
[<EnderIO:blockFusedQuartz>, <EnderIO:itemMaterial:8>, <EnderIO:blockFusedQuartz>],
[<EnderIO:itemAlloy>, <EnderIO:itemBasicCapacitor:2>, <EnderIO:itemAlloy>]]);
mods.extraUtils.QED.addShapedRecipe(<appliedenergistics2:item.ItemMultiPart:360>, [[<AWWayofTime:demonicSlate>, <Avaritia:Double_Craft>, <AWWayofTime:demonicSlate>],
[<appliedenergistics2:item.ItemMultiMaterial:22>, <appliedenergistics2:item.ItemMultiPart:380>, <appliedenergistics2:item.ItemMultiMaterial:22>],
[<Avaritia:Resource>, <appliedenergistics2:item.ItemMultiMaterial:22>, <Avaritia:Resource>]]);
mods.extraUtils.QED.addShapedRecipe(<appliedenergistics2:item.ItemMultiPart:380>, [[<IC2:itemPartIridium>, <appliedenergistics2:item.ItemMultiPart:200>, <IC2:itemPartIridium>],
[<ExtraUtilities:unstableingot:2>, <EnderIO:itemFrankenSkull:4>, <ExtraUtilities:unstableingot:2>],
[<appliedenergistics2:item.ItemMultiMaterial:22>, <AdvancedSolarPanel:asp_crafting_items:12>, <appliedenergistics2:item.ItemMultiMaterial:22>]]);
mods.extraUtils.QED.addShapedRecipe(<minecraft:nether_star>, [[<minecraft:skull:1>, <minecraft:skull:1>, <minecraft:skull:1>],
[<minecraft:soul_sand>, <minecraft:soul_sand>, <minecraft:soul_sand>],
[null, <minecraft:soul_sand>, null]]);
mods.extraUtils.QED.addShapedRecipe(<divinerpg:rupeeIngot> * 3, [[<divinerpg:rupeeOre>, <minecraft:coal>, null],
[null, null, null],
[null, null, null]]);
mods.extraUtils.QED.addShapedRecipe(<divinerpg:arlemiteIngot> * 3, [[<divinerpg:arlemiteOre>, <minecraft:coal>, null],
[null, null, null],
[null, null, null]]);
mods.thermalexpansion.Sawmill.addRecipe(16000, <TwilightForest:tile.TFRoots:1>, <TwilightForest:item.liveRoot> * 2, <minecraft:stick>, 15);

//botania

recipes.addShaped(<Botania:pool>, [[<Botania:livingrock>, null, <Botania:livingrock>], [<Thaumcraft:blockCosmeticSolid:6>, <Botania:livingrock>, <Thaumcraft:blockCosmeticSolid:6>]]);

mods.botania.ManaInfusion.addAlchemy(<minecraft:redstone>, <ExtraBees:honeyDrop>, 100);
mods.botania.ManaInfusion.addAlchemy(<Thaumcraft:blockWoodenDevice:7> * 4, <Thaumcraft:blockMagicalLog:1>, 7500);
mods.botania.ManaInfusion.addAlchemy(<Thaumcraft:blockWoodenDevice:6> * 4, <Thaumcraft:blockMagicalLog>, 3250);
mods.botania.RuneAltar.addRecipe(<customnpcs:npcRuby>, [<customnpcs:npcDemonicIngot>, <Avaritia:big_pearl>, <DraconicEvolution:wyvernCore>, <Avaritia:big_pearl>, <customnpcs:npcOrb:5>, <Avaritia:big_pearl>, <DraconicEvolution:wyvernCore>, <Avaritia:big_pearl>, <customnpcs:npcDemonicIngot>, <Avaritia:big_pearl>, <DraconicEvolution:wyvernCore>, <Avaritia:big_pearl>, <customnpcs:npcOrb:5>, <Avaritia:big_pearl>, <DraconicEvolution:wyvernCore>, <Avaritia:big_pearl>], 200000000);

//Blood Magic

mods.bloodmagic.Altar.removeRecipe(<AWWayofTime:blankSlate>);
mods.bloodmagic.Altar.addRecipe(<AWWayofTime:blankSlate>, <Thaumcraft:blockCosmeticSolid:6>, 1, 1000, 20, 20);
mods.bloodmagic.Altar.addRecipe(<minecraft:redstone>, <ExtraBees:honeyDrop>, 1 * 4, 100, 5, 5);


