#Coremod SortingIndex override: SortingIndex.<coremod class>=<number> sets a coremod's load order.
#Example: SortingIndex.com.mitchej123.hodgepodge.core.HodgepodgeCore=1
#Tue Jul 07 15:47:30 GMT+07:00 2026
enableSortingIndexOverrides=true
